import type { Metadata } from "next";
import MainNavigation from "@/components/MainNavigation";
import '@/styles/_global.scss';

export const metadata: Metadata = {
  title: "Shelf Esteem",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MainNavigation />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
