import type { Metadata } from "next";
import { AppProps } from 'next/app';

import "@styles/_index.scss";

import Footer from "@components/Footer";
import MainNavigation from "@components/Navigation/MainNav";
import Provider from "@/components/Providers/SessionProvider";
import ThemeProvider from "@/components/Providers/ThemeProvider";

export const metadata: Metadata = {
  title: "Shelf Esteem",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <ThemeProvider>
            <MainNavigation />
            <main>
              {children}
            </main>
            <Footer />
          </ThemeProvider>
        </Provider>
      </body>
    </html>
  );
}
